name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate snake.svg
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4

      - name: Generate snake SVG
        uses: Platane/snk@main
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Push generated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: dist/
          commit_message: 'chore: generate snake animation'
          commit_options: '--no-verify'
          skip_fetch: false
          skip_checkout: false
